name: nfunayo
description: "Expense tracking app."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  logger: ^2.5.0

  # UI and Animations
  fl_chart: ^0.71.0
  lottie: ^2.3.2
  cached_network_image: ^3.2.3
  introduction_screen: ^3.1.2

  # Utilities
  audioplayers: ^6.1.0
  image_picker: ^0.8.7+4
  flutter_image_compress: ^2.4.0
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  http: ^1.3.0
  url_launcher: ^6.1.7
  share_plus: ^11.0.0
  path_provider: ^2.0.11
  permission_handler: ^12.0.1

  # Firebase Packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0

  # Notifications
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0

  # WebView
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.20.0
  telephony: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo1.png
    - assets/images/trivia.png
    - assets/images/profile.png
    - assets/images/log.png
    - assets/images/smk.png
    - assets/images/user.png
    - assets/images/panda.png
    - assets/placeholder.json
    - assets/images/google_logo.png
    - assets/animations/piechart.json
    - assets/animations/success.json
    - assets/animations/add_transaction.json
    - assets/animations/dashboard.json
    - assets/animations/profile.json
    - assets/animations/menu.json
    - assets/animations/add.json
    - assets/animations/avatarx.json
