// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-6wF3zbX1Gz3P6e1p8s2a1bofNh8VpE',
    appId: '1:369483233346:web:a32f96fc4a6f4dd6cfd5db',
    messagingSenderId: '369483233346',
    projectId: 'nfunayo-d5b57',
    authDomain: 'nfunayo-d5b57.firebaseapp.com',
    storageBucket: 'nfunayo-d5b57.firebasestorage.app',
    measurementId: 'G-NKBC7XP6MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCIFbplPC2KOMsKGlrtAMA9_FSFxVIQvU',
    appId: '1:369483233346:android:9c4d42a2c24c1194cfd5db',
    messagingSenderId: '369483233346',
    projectId: 'nfunayo-d5b57',
    storageBucket: 'nfunayo-d5b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAGES5POXQic41mjvfgjJZK6n7YPuym9o',
    appId: '1:369483233346:ios:6aa4745b1fb903d1cfd5db',
    messagingSenderId: '369483233346',
    projectId: 'nfunayo-d5b57',
    storageBucket: 'nfunayo-d5b57.firebasestorage.app',
    androidClientId: '369483233346-ghf08gt51h6l61fed533rsp1005s075g.apps.googleusercontent.com',
    iosClientId: '369483233346-p87098jc8hq71g1o8l94lna2a7h19gt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfunayo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAGES5POXQic41mjvfgjJZK6n7YPuym9o',
    appId: '1:369483233346:ios:6aa4745b1fb903d1cfd5db',
    messagingSenderId: '369483233346',
    projectId: 'nfunayo-d5b57',
    storageBucket: 'nfunayo-d5b57.firebasestorage.app',
    androidClientId: '369483233346-ghf08gt51h6l61fed533rsp1005s075g.apps.googleusercontent.com',
    iosClientId: '369483233346-p87098jc8hq71g1o8l94lna2a7h19gt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfunayo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN-6wF3zbX1Gz3P6e1p8s2a1bofNh8VpE',
    appId: '1:369483233346:web:2f3c526675f70fadcfd5db',
    messagingSenderId: '369483233346',
    projectId: 'nfunayo-d5b57',
    authDomain: 'nfunayo-d5b57.firebaseapp.com',
    storageBucket: 'nfunayo-d5b57.firebasestorage.app',
    measurementId: 'G-NN62VJK6BQ',
  );

}